"""Bitswarm constants."""

PROTOCOL_ID = "bitswarm-1.0-alpha.1"
DEFAULT_PIECE_SIZE = 1_048_576
MAX_PIECE_SIZE = 16 * 1_048_576
MANIFEST_FILENAME = "bitswarm-manifest.json"
PIECE_HASH_ALGORITHM = "sha256"
FILE_ROOT_PATH = "."
MAX_ID_LENGTH = 128
CONTROL_ID_PATTERN = r"^[A-Za-z0-9._~-]+$"
MAX_TRACKER_MANIFESTS_PER_PEER = 256
MAX_TRACKER_PIECES_PER_ANNOUNCE = 65_536
